name: Deploy Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Set up Python environment
      run: python3 -m venv env

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Deploy Cloud Functions
      run: |
        for dir in */ ; do
          if [ -f "$dir/config.json" ]; then
            echo "Deploying function in $dir"
            CONFIG=$(cat "$dir/config.json")

            FUNCTION_NAME=$(echo $CONFIG | jq -r '.functionName')
            ENTRYPOINT=$(echo $CONFIG | jq -r '.entrypoint')
            SCHEDULE_PUBSUB_TOPIC=$(echo $CONFIG | jq -r '.schedule')
            RUNTIME=$(echo $CONFIG | jq -r '.runtime')

            gcloud functions deploy $FUNCTION_NAME \
              --entry-point $ENTRYPOINT \
              --runtime $RUNTIME \
              --trigger-topic $SCHEDULE_PUBSUB_TOPIC \
              --source $dir \
              --project ${{ secrets.GCP_PROJECT_ID }} \
              --max-instances 1 \
              --memory 128MB \
              --timeout 10s \
              --region europe-central2
          fi
        done

    - name: Clean up
      run: |
        echo "Deployment complete!"
